tap 'homebrew/bundle'
tap 'caskroom/cask'

tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'homebrew/core'
tap 'neovim/neovim'

brew 'autoconf'
brew 'automake'
brew 'cmake'
brew 'coreutils'
brew 'gdbm'
brew 'gettext'
brew 'grc'
brew 'libtool'
brew 'pkg-config'
brew 'openssl'
brew 'node'
brew 'pcre'
brew 'spark'
brew 'tree'
brew 'tmux'
brew 'wget'
brew 'zsh'
brew 'neovim'

cask 'font-roboto'
cask 'font-roboto-mono'
cask 'font-source-code-pro'
cask 'font-ubuntu'

cask 'docker'
cask 'brave-browser'
cask 'iterm2'
cask 'spectacle'
cask 'deezer'
cask 'slack'
cask 'zoomus'
cask 'transmission'
